Feature/thomas gg/1737709467 backend exec committees
TritonSE/SI-Website-Revamp pull request #35
Opened 2021-10-16 22:47 UTC by thomas-gg

### Administrative Info
Monday Board ID: 1181608900
Make sure your branch name conforms to: `<feature/staging/hotfix/...>/[username]/[Monday Item ID]-[3-4 word description separated by dashes]`. Otherwise, please rename your branch and create a new PR.

### Changes
Added ExecCommittees Routes
- Post, Get, Put

### Testing
How did you confirm your changes worked? 
- Ran all of the above

### Confirmation of Change 
http://localhost:3000/execCommittees
Post
```
{
    "year": 2020,
    "rank": 1,
    "name": "presidente",
    "position": "president",
    "bio": "I'm the president of this committee",
    "imageLink": "https://google.com",
    "redirectLink": "https://google.com",
    "openInSameTab": false
}
```
Get
Put TODO

2021-10-21 05:37 UTC, jacobayu requested changes
Just a small documentation error, but other then that it looks good to me!

2021-10-21 05:37 UTC, jacobayu commented on db/services/execCommittee.js
> + * @param {object} data -
Pretty small, but I think the parameters of your documentation is off, and should match index(int) and body(object?)

2021-10-21 21:32 UTC, jacobayu approved these changes

2021-10-23 05:01 UTC, Amrit-S approved these changes
lgtm

2021-10-23 05:01 UTC, merged