Feature/amrit s/1778816899 home contact backend sync and population
TritonSE/SI-Website-Revamp pull request #47
Opened 2021-11-17 10:25 UTC by Amrit-S

### Administrative Info
Monday Board ID: 1181608900
Make sure your branch name conforms to: `<feature/staging/hotfix/...>/[username]/[Monday Item ID]-[3-4 word description separated by dashes]`. Otherwise, please rename your branch and create a new PR.

### Changes
What changes did you make?
- Synced Home page to backend (includes News & Events + Branches & Chapters)
- Populated Home & Contact page with relevant site information 
- Created responsive Donate page (PayPal Button synced to Sakyadhita's own account)
- Created Responsive 404 Page 
- Updated Footer (added icons, subpages, and animations)
- Added animations on Home page, Footer, Newsletters, EPubs, and Buddhist Culture/About Us pages
- Updated all image headers to Dhanush's ResourceHeader component for consistency 
- Backend: Made email attribute for Branches & Chapters optional due to client demand 

### Testing
How did you confirm your changes worked? 
- Tested on various screen sizes 

### Confirmation of Change 
<img width="1440" alt="Screen Shot 2021-11-17 at 2 24 00 AM" src="https://user-images.githubusercontent.com/42155577/142183020-cc977618-2d0f-4058-91cb-02baa4bb87de.png">
<img width="1440" alt="Screen Shot 2021-11-17 at 2 23 21 AM" src="https://user-images.githubusercontent.com/42155577/142183052-15610d87-968a-49b5-bfbd-3c2d252cbc63.png">
<img width="1439" alt="Screen Shot 2021-11-17 at 2 23 43 AM" src="https://user-images.githubusercontent.com/42155577/142183066-e0099137-e24f-465b-bc94-54d43e87e7ca.png">

2021-11-18 04:51 UTC, amiteshksharma requested changes
Nice PR. Gotta say the underline color change on hover for the footer elements is spicy. Couple of things though: 

1) When you click on a location marker and then scroll, the little pop-up stays on the screen and you can have something like this show up. Probably not an ideal feature but if you want it then it is what it is. 

![image](https://user-images.githubusercontent.com/51978213/142352902-6f7b2ca5-330e-4e45-878e-30f5e19c7c37.png)

2) I assume you know but just want to write it down, some image URLs do not work on the donate page. 

![image](https://user-images.githubusercontent.com/51978213/142353151-aeee0665-0585-48ec-8a91-d59ca891135f.png)

3) Not sure if this change was part of your PR or not, but for Buddhist Culture the side navbar starts inside the header photo as seen below. 

![image](https://user-images.githubusercontent.com/51978213/142353317-e608a1a4-1990-472b-b3e9-1de3198a0542.png)

4) For the Join us, Volunteer, and Donate page, there is a circle in the bottom right of the image header but I can't click it or anything, so is there a reason for this? or is it just to indicate to scroll down

![image](https://user-images.githubusercontent.com/51978213/142353541-72cdb61c-f1ed-48dd-988e-439c912e30fa.png)

5) Also, for the header on "Join us", "Donate & Support", and "Volunteer", we have the filler text with random words. I assume you are waiting on them to add the proper text but I'll write it down here just so we remember. 

![image](https://user-images.githubusercontent.com/51978213/142353770-78903d58-88f8-4eb6-b6d0-241c93d04634.png)

2021-11-20 21:21 UTC, aaron-kirk commented
the slider thing was still broken for me so I changed it such that I think it should be fixed? works for me at least...

sorry for my hacky code 😅😅

2021-11-21 12:03 UTC, amiteshksharma commented on seeds/models/newsAndEvents.js
> +                    "https://sakyadhita.org/docs/resources/newsletters/2021%20Sakyadhita%20Newsletter%20Vol.%2029.pdf",
Is someone else adding newsletters to the dropbox?

2021-11-24 08:26 UTC, aaron-kirk approved these changes
LPTM -- so much stuff, but I couldn't really find any issues. This is why you're the #1 PM.
(A couple conflicts need resolving, though, before merging)

2021-11-24 09:36 UTC, amiteshksharma approved these changes
What a great PR. A couple of small bugs at the start, but what a great comeback here. You really pulled not only your weight, but the weight of the whole damn team. I am thoroughly impressed by the work done in this PR. Can't wait to merge this into main and get one step closer to finishing this project! Great job Amrit, where would this team be without your experience, expertise, and guidance.

2021-11-24 09:41 UTC, merged